### ISSUE TITLE
Unable to import in python 3.12

### ISSUE THREAD

**Issue by Were-Woof** [WillofSteel-Devs/api-wrapper#1]
After running:
```
pip install willofsteel
```

I got the expected message: 
```
Successfully built willofsteel
Installing collected packages: willofsteel
Successfully installed willofsteel-0.0.1
```

However after trying to import it within python 3.12, I got the following error:
```
Python 3.12.0 (<REDACTED>) [REDACTED ()] on win32
Type "help", "copyright", "credits" or "license" for more information.
> import willofsteel
> Traceback (most recent call last):
> <REDACTED>
>     from .types import Player, Alliance
> ModuleNotFoundError: No module named 'willofsteel.types'
```

**Comment by Were-Woof** [comment]
![Screenshot 2024-02-17 144605](https://github.com/WillofSteel-Devs/api-wrapper/assets/118316858/f1d957d6-db00-48b0-871b-4dbdafcc2f1e)

Checked the files I got from installing, it looks like I didn't get the entire project from pip

**Comment by ItsNeil17** [comment]
This iss
